### ISSUE TITLE
Homey 1.5.8 not receiving snapshots in Telegram

### ISSUE THREAD

**Issue by Flight777** [j0bro/com.ubnt.unifivideo#10] opened 2018-03-24 13:25 UTC
Since my upgrade to 1.5.8 I'm not able to receive snapshots anymore of my g3 in Telegram.

**Comment by j0bro** [comment] 2018-03-26 07:14
Will take a look as soon as I have time and the same software version!

**Comment by Flight777** [comment] 2018-03-26 10:56
Thanks 👍

**Comment by j0bro** [comment] 2018-05-09 15:09
Is this still occurring in 1.5.9? Has the Telegram app been changed in any way that you know of maybe?

**Comment by Flight777** [comment] 2018-09-09 11:50
Yes unfortunately still an issue. No I don't know the details of the Telegram app :(

**Comment by j0bro** [comment] 2019-01-16 09:04
I tested this functionality using Unifi Video v0.9.2 on Homey 2.0.0 with the Telegram app v0.2.6 and I can confirm it works. Since upgrading Homey to v2.0.0 is very much advised at this point, I am closing this issue.

**Closed as completed by j0bro** 2019-01-16 09:04 UTC

**Comment by Flight777** [comment] 2019-01-16 20:50
Hi Jeroen,

I tried again as well but it is still not working, am I doing something wrong?

Screenshot of flow: https://ibb.co/4TtfsR0
